@ProductApi_HostAddress = http://localhost:7000

GET {{ProductApi_HostAddress}}/api/product
Accept: application/json

###

POST {{ProductApi_HostAddress}}/api/product
Content-Type: application/json

{
  "id": 1,
  "name": "Apple",
  "price": 1.30
}

###
